solar_vendors = [
    {
        "id": "sunrise-energy",
        "name": "Sunrise Energy Solutions",
        "rating": 4.6,
        "price_range_inr": "₹65k – ₹75k / kW (turnkey)",
        "base_price_per_kw_inr": 68000,
        "locations": ["Delhi", "Noida", "Gurugram"],
        "years_experience": 9,
        "highlights": ["MNRE empanelled", "Net-meter support", "24x7 monitoring"],
        "contact": "+91-98765-43210",
        "website": "https://sunriseenergy.example.com",
    },
    {
        "id": "surya-grid",
        "name": "SuryaGrid EPC",
        "rating": 4.3,
        "price_range_inr": "₹58k – ₹70k / kW",
        "base_price_per_kw_inr": 61000,
        "locations": ["Mumbai", "Pune", "Nashik"],
        "years_experience": 12,
        "highlights": ["Hybrid inverter experts", "O&M packages", "Battery integration"],
        "contact": "+91-99887-77665",
        "website": "https://suryagrid.example.com",
    },
    {
        "id": "greenbeam",
        "name": "GreenBeam Solar",
        "rating": 4.8,
        "price_range_inr": "₹62k – ₹80k / kW",
        "base_price_per_kw_inr": 67000,
        "locations": ["Ahmedabad", "Vadodara", "Surat"],
        "years_experience": 7,
        "highlights": ["5-year O&M included", "Real-time app", "EMI options"],
        "contact": "care@greenbeam.example.com",
        "website": "https://greenbeam.example.com",
    },
    {
        "id": "agripower",
        "name": "AgriPower Pumps",
        "rating": 4.2,
        "price_range_inr": "₹3.2L – ₹4.5L per 5HP pump",
        "base_price_per_kw_inr": 64000,
        "locations": ["Jaipur", "Udaipur", "Indore"],
        "years_experience": 11,
        "highlights": ["PM-KUSUM specialists", "RBI/NABARD loan support", "On-field service"],
        "contact": "+91-90909-80807",
        "website": "https://agripower.example.com",
    },
    {
        "id": "urban-spark",
        "name": "UrbanSpark Rooftech",
        "rating": 4.5,
        "price_range_inr": "₹55k – ₹68k / kW",
        "base_price_per_kw_inr": 59000,
        "locations": ["Bengaluru", "Mysuru", "Hyderabad"],
        "years_experience": 8,
        "highlights": ["Remote diagnostics", "Smart EV-ready", "Rapid installation"],
        "contact": "hello@urbanspark.example.com",
        "website": "https://urbanspark.example.com",
    },
]
