"""add subsidy submission model

Revision ID: a1b2c3d4e5f6
Revises: c0e15b8ba52a
Create Date: 2025-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'c0e15b8ba52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsidy_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roof_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_bill', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('consumer_segment', sa.String(length=80), nullable=True),
    sa.Column('grid_connection', sa.String(length=80), nullable=True),
    sa.Column('roof_type', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subsidy_submission')
    # ### end Alembic commands ###

