"""add journey completed flag

Revision ID: bd3c64a01c0a
Revises: 4d6335b92df4
Create Date: 2025-11-12 00:21:08.955812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3c64a01c0a'
down_revision = '4d6335b92df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journey_completed', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('journey_completed')

    # ### end Alembic commands ###
