"""store last subsidy summary

Revision ID: c0e15b8ba52a
Revises: 3fbdaa8c5851
Create Date: 2025-11-12 01:47:36.594766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e15b8ba52a'
down_revision = '3fbdaa8c5851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_system_kw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_net_cost_inr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_estimated_savings_inr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_estimate_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_estimate_updated_at')
        batch_op.drop_column('last_estimated_savings_inr')
        batch_op.drop_column('last_net_cost_inr')
        batch_op.drop_column('last_system_kw')

    # ### end Alembic commands ###
